# Three Nodes, One Egress IP Configuration
# All three nodes (lenovo-204/205/206) share one IP (93.85.81.204) for load balancing

---
# Node labels for all three egress gateway nodes
apiVersion: v1
kind: Node
metadata:
  name: lenovo-204
  labels:
    node-role.kubernetes.io/egress: ""
    egress-gateway: "primary"
    zone: "zone-a"
spec: {}
---
apiVersion: v1
kind: Node
metadata:
  name: lenovo-205
  labels:
    node-role.kubernetes.io/egress: ""
    egress-gateway: "secondary"
    zone: "zone-b"
spec: {}
---
apiVersion: v1
kind: Node
metadata:
  name: lenovo-206
  labels:
    node-role.kubernetes.io/egress: ""
    egress-gateway: "tertiary"
    zone: "zone-c"
spec: {}

---
# BGP Peering Policy for all three egress nodes
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: three-nodes-bgp-peering
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/egress: ""
  virtualRouters:
  - localASN: 65017
    exportPodCIDR: true
    exportServices: true
    neighbors:
    - peerAddress: '93.85.81.201/29'
      peerASN: 6697
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
    - peerAddress: '93.85.81.202/29'
      peerASN: 6697
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30

---
# Single IP Pool for egress gateway
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: shared-egress-pool
  namespace: kube-system
spec:
  cidrs:
  - cidr: "93.85.81.204/32"

---
# BGP Advertisement for single egress IP
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPolicy
metadata:
  name: shared-egress-advertisement
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/egress: ""
  virtualRouters:
  - localASN: 65017
    neighbors:
    - peerAddress: '93.85.81.201/29'
      peerASN: 6697
    - peerAddress: '93.85.81.202/29'
      peerASN: 6697
    serviceAdvertisements:
    - addresses:
      - "93.85.81.204"
      communities:
      - "65017:100"

---
# Single Egress Gateway Policy
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: shared-egress-policy
  namespace: kube-system
spec:
  selectors:
  - namespaceSelector:
      matchLabels:
        name: apk-system
  destinationCIDRs:
  - "0.0.0.0/0"
  egressGateway:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/egress: ""
    interface: "eth0"
    egressIP: "93.85.81.204"

---
# LoadBalancer Service with single egress IP
apiVersion: v1
kind: Service
metadata:
  name: egress-gateway-service
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: "0.0.0.0/0"
    cilium.io/loadbalancer-ip-pool: "shared-egress-pool"
spec:
  type: LoadBalancer
  loadBalancerClass: "cilium"
  loadBalancerIP: "93.85.81.204"
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: egress-gateway

---
# Network Policy for egress traffic
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: egress-traffic-policy
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: apk-system
  egress:
  - toEntities:
    - world
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
      - port: "53"
        protocol: TCP
      - port: "53"
        protocol: UDP
    - ports:
      - port: "22"
        protocol: TCP
      - port: "179"
        protocol: TCP  # BGP
    toCIDR:
    - "93.85.81.201/29"  # BGP peer 1
    - "93.85.81.202/29"  # BGP peer 2

---
# ConfigMap for single egress configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-egress-config
  namespace: kube-system
data:
  config.yaml: |
    egress_gateway:
      enabled: true
      shared_ip: "93.85.81.204"
      interface: "eth0"
      nodes:
        - name: "lenovo-204"
          priority: 1
        - name: "lenovo-205"
          priority: 2
        - name: "lenovo-206"
          priority: 3
      
    bgp:
      enabled: true
      localASN: 65017
      egress_ip: "93.85.81.204"
      community: "65017:100"
      neighbors:
        - peerAddress: "93.85.81.201/29"
          peerASN: 6697
        - peerAddress: "93.85.81.202/29"
          peerASN: 6697
      
    routing:
      export_pod_cidr: true
      export_services: true
      export_egress_ip: true

---
# DaemonSet for single egress gateway
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: shared-egress-gateway
  namespace: kube-system
  labels:
    app: shared-egress-gateway
spec:
  selector:
    matchLabels:
      app: shared-egress-gateway
  template:
    metadata:
      labels:
        app: shared-egress-gateway
      annotations:
        cilium.io/egress-gateway: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/egress: ""
      containers:
      - name: cilium-egress-gateway
        image: cilium/cilium:latest
        command:
        - cilium
        - egress-gateway
        - --config-dir=/etc/cilium
        - --bgp-enabled=true
        - --egress-gateway-enabled=true
        - --egress-ip=93.85.81.204
        env:
        - name: CILIUM_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: EGRESS_IP
          value: "93.85.81.204"
        volumeMounts:
        - name: cilium-config
          mountPath: /etc/cilium
        - name: cilium-run
          mountPath: /var/run/cilium
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: bpf-maps
          mountPath: /sys/fs/bpf
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: cilium-config
        configMap:
          name: single-egress-config
      - name: cilium-run
        hostPath:
          path: /var/run/cilium
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: bpf-maps
        hostPath:
          path: /sys/fs/bpf
      hostNetwork: true
      tolerations:
      - operator: Exists
