apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
spec:
  nodeSelector:
    matchLabels:
      bgp-policy: a
  virtualRouters:
  - localASN: 65017
    exportPodCIDR: true
    neighbors:
    - peerAddress: '93.85.81.201/29'
      peerASN: 6697
    - peerAddress: '93.85.81.202/29'
      peerASN: 6697


