# =================================================================
# StarRocks Helm Values - ClusterIP + Dynamic PVC
# =================================================================
# Использование:
#   helm install starrocks starrocks/kube-starrocks \
#     -n starrocks -f starrocks-values.yaml
#
# Доступ снаружи кластера через port-forward:
#   kubectl port-forward -n starrocks svc/starrocks-fe-service 9030:9030
#   mysql -h 127.0.0.1 -P 9030 -u root -p
# =================================================================

# --- Общие настройки ---
starrocks:
  # Установка пароля для root пользователя
  initPassword:
    enabled: true
    # Секрет должен быть создан заранее:
    # kubectl create secret generic starrocks-root-pass \
    #   --from-literal=password='YourStrongPassword123!' -n starrocks
    passwordSecret: starrocks-root-pass

  # --- Frontend (FE) Configuration ---
  starrocksFESpec:
    # Высокая доступность - 3 реплики
    replicas: 3
    
    # Образ StarRocks FE
    image:
      repository: starrocks/fe-ubuntu
      tag: "4.0-latest"
      #tag: "3.3-latest"  # Stable version, tested with operator v1.11.3
    
    # Ресурсы для FE
    resources:
      requests:
        cpu: 500m      # 0.5 CPU
        memory: 2Gi    # 2 GB RAM
      limits:
        cpu: 2         # 2 CPU
        memory: 4Gi    # 4 GB RAM
    
    # Хранилище (динамические PVC через storageVolumes)
    storageVolumes:
      - name: fe-meta
        storageClassName: "microk8s-hostpath"
        storageSize: 20Gi
        mountPath: /opt/starrocks/fe/meta
      - name: fe-log
        storageClassName: "microk8s-hostpath"
        storageSize: 1Gi
        mountPath: /opt/starrocks/fe/log
      
    # ClusterIP для доступа внутри кластера
    service:
      type: ClusterIP
      clusterIP: 10.152.183.151  # Статический IP (закомментировано - может конфликтовать)
      ports:
        # MySQL протокол (query_port)
        - name: query
          port: 9030
          containerPort: 9030
        # HTTP API и Web UI
        - name: http
          port: 8030
          containerPort: 8030

  # --- Backend (BE) Configuration ---
  starrocksBeSpec:
    # Высокая доступность - 3 реплики
    replicas: 3
    
    # Образ StarRocks BE
    image:
      repository: starrocks/be-ubuntu
      tag: "4.0-latest"
      #tag: "3.3-latest"  # Must match FE version
    
    # Ресурсы для BE
    resources:
      requests:
        cpu: 1         # 1 CPU
        memory: 4Gi    # 4 GB RAM
      limits:
        cpu: 4         # 4 CPU
        memory: 8Gi    # 8 GB RAM
    
    # Хранилище (динамические PVC через storageVolumes)
    storageVolumes:
      - name: be-data
        storageClassName: "microk8s-hostpath"
        storageSize: 100Gi
        mountPath: /opt/starrocks/be/storage
      - name: be-log
        storageClassName: "microk8s-hostpath"
        storageSize: 1Gi
        mountPath: /opt/starrocks/be/log
    
    # ClusterIP для доступа внутри кластера
    service:
      type: ClusterIP
      clusterIP: 10.152.183.152  # Статический IP (закомментировано - может конфликтовать)
      ports:
        # BE порт для загрузки данных
        - name: be
          port: 9060
          containerPort: 9060
        # BE WebServer
        - name: webserver
          port: 8040
          containerPort: 8040
        # Heartbeat порт (internal)
        - name: heartbeat
          port: 9050
          containerPort: 9050
        # BRPC порт (internal)
        - name: brpc
          port: 8060
          containerPort: 8060

# --- Operator Configuration ---
operator:
  # Образ StarRocks оператора
  image:
    repository: starrocks/operator
    tag: "v1.11.3"
  
  # Ресурсы для оператора
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

